#!/bin/bash

## i3 panel config. Powerline style.
## Based on Electro7's work
## Modded by demure

panel_fifo="/tmp/i3_lemonbar_${USER}"
geometry="x44"
res_w=$(xrandr | awk '/current/ {print $8a}')

## Will limit the char length of music, adjust down for smaller screens.
music_limit=70

## This format needs a fork of lemonbar, which supports xft fonts.
## The font should have powerline support, if you want the fancy separators.
font="Meslo LG M DZ Regular for Powerline-14"

## I recommend font awesome for the iconfont, it has the best icon support
## I have even of any symbol font. It also has the most symbols.
iconfont="fontawesome-12"

## This is for the Screenshot IP Scrubber
## You could set this to "" to reduce bar length while toggled.
scrub_ip="---.---.---.---"

## Battery
## Note: levels higher than 'high' will not be highlighted.
bat_alert_low=11
bat_alert_mid=22
bat_alert_high=33
### End Alarm ### }}}

### Update Settings ### {{{
# update setting, in seconds (conky update in i3_lemonbar_conky)
upd_vol=3                           ## Volume update
upd_bri=3                           ## Screen brightness update
upd_tmb=60                          ## Thinkpad Multi Battery update
### End Update ### }}}

### Color ### {{{
color_underline="#FF76b9ed"
color_back="#FF000000"               ## Default background
color_fore="#FFFFFFFF"               ## Default foreground
color_workspace_selected_bg="#FF474B4F"
color_workspace_active_bg="#FF272727"

color_head="#FF000000"              ## Background for first element
color_sec_b1="#FF282A2E"            ## Background for section 1
color_sec_b2="#FF454A4F"            ## Background for section 2
color_icon="#FF979997"              ## For icons
color_bat_low="#ffdc322f"           ## Background for low bat threshold
color_bat_mid="#ffcb4b16"           ## Background for mid bat threshold
color_bat_high="#ffb58900"          ## Icon for high bat threshold
color_bat_plug="#ff859900"          ## Forground for 70-100 battery icon

	### Solarized ### {{{
	## For reference purposes
	#$base03:    #002b36;
	#$base02:    #073642;
	#$base01:    #586e75;
	#$base00:    #657b83;
	#$base0:     #839496;
	#$base1:     #93a1a1;
	#$base2:     #eee8d5;
	#$base3:     #fdf6e3;
	#$yellow:    #b58900;
	#$orange:    #cb4b16;
	#$red:       #dc322f;
	#$magenta:   #d33682;
	#$violet:    #6c71c4;
	#$blue:      #268bd2;
	#$cyan:      #2aa198;
	#$green:     #859900;
	### End Solarized ### }}}
### End Color ### }}}

### Spacing ### {{{
##default space between sections
#if [ ${res_w} -gt 1366 ]; then
  #stab=' '
#else
  #stab=''
#fi

## Spacing between blocks
stab='  '
### End Spacing ### }}}

### Icons ### {{{
# Char glyps for powerline fonts
sep_left=" "                        ## Powerline separator left
sep_right=" "                       ## Powerline separator right
#sep_l_left=" "                      ## Powerline light separator left
#sep_l_right=" "                     ## Powerline light sepatator right
pixels_underline=3

# Icon glyphs from Font Awesome
icon_clock=""                      ## Clock icon
icon_cpu=""                        ## CPU icon
#icon_cpu=""                        ## CPU icon
icon_mem=""                        ## MEM icon
icon_dl=""                         ## Download icon
icon_ul=""                         ## Upload icon
icon_vol=""                        ## Volume icon
icon_bri=""                        ## Brightness icon
icon_hd=""                         ## HD / icon
icon_home=""                       ## HD /home icon
icon_mail=""                       ## Mail icon
icon_mail_read=""                  ## Mail read icon
icon_chat=""                       ## IRC/Chat icon
icon_music=""                      ## Music icon
icon_prog=""                       ## Window icon
icon_contact=""                    ## Contact icon
icon_wsp=""                        ## Workspace icon
icon_bat_plug=""                   ## Battery icon, may add level indicator? and plugged in?
icon_bat0=""                       ## Battery icon
icon_bat1=""                       ## Battery icon
icon_bat2=""                       ## Battery icon
icon_bat3=""                       ## Battery icon
icon_bat4=""                       ## Battery icon
icon_temp=""                       ## Temperature icon
icon_wifi=""                       ## Wifi percent icon
icon_local_eth=""                  ## Local IP eth icon
icon_local_wifi=""                 ## Local IP wifi icon
icon_local_out=""                  ## Local IP out icon
icon_ext_ip=""                     ## External IP
icon_gpg=""                        ## GPG icon
icon_gpg_locked=""                 ## GPG locked icon
icon_gpg_unlocked=""               ## GPG unlocked icon
icon_vpn=""                        ## VPN icon
### End Icons ### }}}
